### ISSUE TITLE
ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by TianshuDing** [tczpl/XBlock-ETH#4]
Select the datasets to download:
0. All
1. Block
2. Block Transaction
3. Internal Transaction 
4. Contract Info
5. ERC20 Transaction
6. ERC721 Transaction
7. Token Info
Please input a number (0~6): 2
------------------------------------------------------------
Downloading 0to999999_BlockTransaction.zip 110.77 MB
100.0% - 1.23 MB/s - 110.77 MB          
------------------------------------------------------------
Downloading 1000000to1999999_BlockTransaction.zip 452.85 MB
100.0% - 1.19 MB/s - 452.85 MB          
------------------------------------------------------------
Downloading 2000000to2999999_BlockTransaction.zip 516.45 MB
Traceback (most recent call last):
  File "E:/Papers/XBlock-ETH/download.py", line 210, in <module>
    start()
  File "E:/Papers/XBlock-ETH/download.py", line 191, in start
    download(localFile, srcUrl)
  File "E:/Papers/XBlock-ETH/download.py", line 22, in download
    line = line % (downSize/contentLength*100, downSize/1024/1024/(time.time()-startTime), downSize/1024/1024)
ZeroDivisionError: float division by zero

Process finished with exit code 1

**Comment by tczpl** [comment]
好像已经被另一个老哥的PR修复了？
